###

POST http://localhost:4000/subscribers
Content-Type: application/json

{
    "name": "50 Days Leetcode Badge😃 ",
    "subscribedToChannel": "Leetcode"
}



###
GET http://localhost:4000/subscribers
###
GET http://localhost:4000/subscribers/66a0f963b05bd4d5382521be



###
PATCH http://localhost:4000/subscribers/66a0f963b05bd4d5382521be
Content-Type: application/json

{
    "name": "Artist🏜️"
}



###
DELETE http://localhost:4000/subscribers/66a0f963b05bd4d5382521be